<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.1;net6;net8</TargetFrameworks>
    <LangVersion>11</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <EnablePreviewFeatures>false</EnablePreviewFeatures>
    <Configurations>Debug;Release</Configurations>
    <Platforms>AnyCPU</Platforms>
    <NoWarn>1701;1702;1591;CS8618;</NoWarn>
    <AssemblyName>Cross.EdiEngine.Common</AssemblyName>
    <Description>Edi Engine comon library</Description>
    <RepositoryUrl>https://github.com/denis-peshkov/Cross.EdiEngine</RepositoryUrl>
    <PackageProjectUrl>https://github.com/denis-peshkov/Cross.EdiEngine</PackageProjectUrl>
    <AssemblyVersion>1.7.0.0</AssemblyVersion>
    <FileVersion>1.7.0.0</FileVersion>
    <Version>1.7.0.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0" PrivateAssets="All" />
  </ItemGroup>

</Project>
