<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.1;net6.0;net7.0;net8.0</TargetFrameworks>
    <LangVersion>11</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <EnablePreviewFeatures>false</EnablePreviewFeatures>
    <Configurations>Debug;Release</Configurations>
    <Platforms>AnyCPU</Platforms>
    <NoWarn>1701;1702;1591;CS8618;</NoWarn>
    <AssemblyName>Cross.EdiEngine</AssemblyName>
    <Description>Edi Engine main library</Description>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <Target Name="DeleteBinObjFolders" BeforeTargets="Clean">
    <RemoveDir Directories=".\bin" />
    <Delete Files=".\obj\**\*.cs" />
  </Target>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.2" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.2" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="8.0.0" />
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" Version="8.2.1" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.2.1" />
    <PackageReference Include="System.Text.Json" Version="8.0.6" />
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EdiEngine.Common\EdiEngine.Common.csproj" />
    <ProjectReference Include="..\EdiStandards\X12_004010\X12_004010.csproj" PrivateAssets="All" />
  </ItemGroup>

</Project>
